### ISSUE TITLE
converting prolog code to pydatalog

### ISSUE THREAD

**Issue by earney** [pcarbonn/pyDatalog#10]
As an exercise, I'm trying to convert the tic tac toe prolog program at https://courses.cs.washington.edu/courses/cse341/03sp/slides/PrologEx/tictactoe.pl.txt  to pydatalog.  Any advice on how the syntax would need to change to make that happen?

For example I have converted
rowwin(Board, Player) :- Board = [Player,Player,Player,_,_,_,_,_,_].
to
rowwin(Board, Player) <= Board == [Player,Player,Player,_,_,_,_,_,_]

but still get an error stating 'Invalid body for clause'.

Thanks!

**Comment by pcarbonn** [comment]
Hi Billy !

You need to put parenthesis around the equality clause :

rowwin(Board, Player) <= *( *Board == [Player,Player,Player,*,*,*,*,*,*] *)*

**Comment by earney** [comment]
Thanks!
