### ISSUE TITLE
The following neither yields nor terminates

### ISSUE THREAD

**Issue by robertsimione** [pcarbonn/pyDatalog#16]
from pyDatalog import pyDatalog
    pyDatalog.create_terms('factorial, N')

    factorial[N] = N*factorial[N-1]
    factorial[1] = 1

    print((N.in_(range(1, 4)) & factorial[N]==6))

**Comment by pcarbonn** [comment]
To prevent infinite loops, you need to write this :

    from pyDatalog import pyDatalog
    pyDatalog.create_terms('factorial, N, F')

    (factorial[N] == F) <= (N > 1) & (F == N*factorial[N-1])
    factorial[1] = 1

    print((N.in_(range(1, 4)) & (factorial[N]==6)))

**Comment by robertsimione** [comment]
Thank you!
