### ISSUE TITLE
Strange behavior with in_ loop in predicates

### ISSUE THREAD

**Issue by FlorianWilhelm** [pcarbonn/pyDatalog#21]
Let's assume I want to define predicates of two digit numbers like `digit((X0,X1))` with:
```
@pyDatalog.program()
def _():
    digits(X) <= X[0].in_(range(10)) & X[1].in_(range(10)) 
    print(digits((X0,X1)))
```
then I get the expected output:
```
X0 | X1
---|---
4  | 3 
0  | 1 
1  | 3 
7  | 2 
4  | 0 
....
```
But if I want to write this with a loop like
```
@pyDatalog.program()
def _():
    digits(X) <= Z.in_(range(2)) & X[Z].in_(range(10))
    print(digits((X0,X1)))
```
I just get `True` as an answer. I don't understand why I just see `True` and why this does  not work. Can you shed some light on this or is it a bug maybe?

**Comment by pcarbonn** [comment]
That's because X0 and X1 are not fully defined by the second program.  digits(X) is true if there is a value of Z such that the tail is true.  Indeed, 1 is a possible value of Z.  2 is another that could be reached by backtracking.  But only one value is used at a time.  Hence, only X0 or X1 is defined.  In that case, pyDatalog says True.

**Comment by FlorianWilhelm** [comment]
@pcarbonn, thanks for the fast reply. So if a bound variable appears only on the right hand side like `Z` then I must read it as existential quantification? Okay, got that. 
I really like your code in `examples/queens_N.py` since everything is really concise and you don't repeat yourself as in the tutorial's solution of the Queens-problem. For instance you only state once that the possible position in one row is in range 1 to 8. 
Right now I am trying to solve one of those crosswords like problems where you put digits in a matrix and have a lot of conditions like "number in the row 1 is the squared number of row 5" etc. I am thinking of a smart way to say that each element of the matrix is in range 0 to 9 for all 36 elements in the matrix without repeating this with every condition. Maybe it just takes some more time for me to get the hang of this declarative way of programming.

**Comment by pcarbonn** [comment]
Quite often, loops are represented recursively in prolog / datalog : 
digits(X) <= X[0].in_(range(10)) & digits(X[1:])

**Comment by FlorianWilhelm** [comment]
Thanks, I'll close this issue then.
