### ISSUE TITLE
Where are the tests ?

### ISSUE THREAD

**Issue by sfermigier** [pcarbonn/pyDatalog#37]
On https://sites.google.com/site/pydatalog/home I read: "(over 400 tests)" (with a link to a defunct site).

Have these tests been lost in the transition to GitHub ?

Same for the content of the site itself (https://sites.google.com/site/pydatalog/home): the /docs/ directory is mostly empty.

**Comment by pcarbonn** [comment]
The tests are in [/pyDatalog/examples/test.py](https://github.com/pcarbonn/pyDatalog/blob/master/pyDatalog/examples/test.py)

The content of the site is not in this repository but managed by [Google Sites](https://sites.google.com/u/0/new?authuser=0).

**Comment by sfermigier** [comment]
Thanks.
