### ISSUE TITLE
pip-Win uninstall options missing?

### ISSUE THREAD

**Issue by Makitk** [pcarbonn/pyDatalog#7]
The following are missing:
Commandline: "pip uninstall all" OR "pip uninstall *" to uninstall all packages previously installed by pip.
pip-win GUI: No ability to uninstall packages previously installed by pip. No ability to uninstall pip itself.
Windows 7: Programs & Features-recognizable uninstaller for pip.
All: Any uninstall option for pip.

The short of it; I installed pip for a program I thought I needed, didn't, uninstalled said program, dependencies of said program remained, pip remains, found no uninstall option, am annoyed.
Fix the above. Give me an uninstaller.

**Comment by pcarbonn** [comment]
You seem to be complaining about pip, not pip-Win.  Furthermore, this site is about pyDatalog, not pip-win.

**Comment by Makitk** [comment]
pip-win site forwarded me here for support. Go complain to them.
